/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/user/index'
import { Route as SignupIndexImport } from './routes/signup/index'
import { Route as SignoutIndexImport } from './routes/signout/index'
import { Route as NosotrosIndexImport } from './routes/nosotros/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as FaqsIndexImport } from './routes/faqs/index'
import { Route as EventosIndexImport } from './routes/eventos/index'
import { Route as DebugIndexImport } from './routes/debug/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as LoginVerifyImport } from './routes/login/verify'
import { Route as LoginForgotImport } from './routes/login/forgot'
import { Route as ErrorCodnameImport } from './routes/error/$codname'
import { Route as BlogIdImport } from './routes/blog/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const SignoutIndexRoute = SignoutIndexImport.update({
  path: '/signout/',
  getParentRoute: () => rootRoute,
} as any)

const NosotrosIndexRoute = NosotrosIndexImport.update({
  path: '/nosotros/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const FaqsIndexRoute = FaqsIndexImport.update({
  path: '/faqs/',
  getParentRoute: () => rootRoute,
} as any)

const EventosIndexRoute = EventosIndexImport.update({
  path: '/eventos/',
  getParentRoute: () => rootRoute,
} as any)

const DebugIndexRoute = DebugIndexImport.update({
  path: '/debug/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const LoginVerifyRoute = LoginVerifyImport.update({
  path: '/login/verify',
  getParentRoute: () => rootRoute,
} as any)

const LoginForgotRoute = LoginForgotImport.update({
  path: '/login/forgot',
  getParentRoute: () => rootRoute,
} as any)

const ErrorCodnameRoute = ErrorCodnameImport.update({
  path: '/error/$codname',
  getParentRoute: () => rootRoute,
} as any)

const BlogIdRoute = BlogIdImport.update({
  path: '/blog/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/$id': {
      preLoaderRoute: typeof BlogIdImport
      parentRoute: typeof rootRoute
    }
    '/error/$codname': {
      preLoaderRoute: typeof ErrorCodnameImport
      parentRoute: typeof rootRoute
    }
    '/login/forgot': {
      preLoaderRoute: typeof LoginForgotImport
      parentRoute: typeof rootRoute
    }
    '/login/verify': {
      preLoaderRoute: typeof LoginVerifyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/debug/': {
      preLoaderRoute: typeof DebugIndexImport
      parentRoute: typeof rootRoute
    }
    '/eventos/': {
      preLoaderRoute: typeof EventosIndexImport
      parentRoute: typeof rootRoute
    }
    '/faqs/': {
      preLoaderRoute: typeof FaqsIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/nosotros/': {
      preLoaderRoute: typeof NosotrosIndexImport
      parentRoute: typeof rootRoute
    }
    '/signout/': {
      preLoaderRoute: typeof SignoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/': {
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BlogIdRoute,
  ErrorCodnameRoute,
  LoginForgotRoute,
  LoginVerifyRoute,
  AdminIndexRoute,
  BlogIndexRoute,
  DebugIndexRoute,
  EventosIndexRoute,
  FaqsIndexRoute,
  LoginIndexRoute,
  NosotrosIndexRoute,
  SignoutIndexRoute,
  SignupIndexRoute,
  UserIndexRoute,
])

/* prettier-ignore-end */
